sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t teopatl/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true teopatl/react-test npm test

after_success:
  - docker build -t teopatl/multi-client ./client
  - docker build -t teopatl/multi-nginx ./nginx
  - docker build -t teopatl/multi-server ./server
  - docker build -t teopatl/multi-worker ./worker
  # log in to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
  #push to docker hub
  - docker push teopatl/multi-client
  - docker push teopatl/multi-nginx
  - docker push teopatl/multi-server
  - docker push teopatl/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'Multi-docker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-129627414647'
  bucket_path: 'docker-multi'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
