sudo: required
services:
  - docker

before_install:
  - docker build -t teopatl/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run teopatl/react-test npm test -- --coverage

after_success:
  - docker build -t teopatl/multi-client ./client
  - docker build -t teopatl/multi-nginx ./nginx
  - docker build -t teopatl/multi-server ./server
  - docker build -t teopatl/multi-worker ./worker
